### ISSUE TITLE
metasploit?

### ISSUE THREAD

**Issue by Mr-613** [pagekite/PyPagekite#104]
Sorry I'm kind of a pleb and a beginner but , I used to use ngrok until my isp started to Block it so I switched to pagekite . I'm currently learning ethical hacking and I want to hack my phone , is there any way that I can set a specific port on the web page, and on ngrok I used to run "ngrok tcp 61300" so how does tcp port forwarding work on pagekite
 for e.g

https://pythonrep.pagekite.me:61300
is this possible?!
and if not are there any alternatives because metasploit asks for a LPORT and a LHOST , also when I port forward on ngrok it would show something like , 127.0.0.1:8298 -->0.tcp.ngrok.io:556 so can I get it to work that way

**Comment by airjordan93** [comment]
+1 same question

**Comment by BjarniRunar** [comment]
No, PageKite can not forward arbitrary ports and it is not on our roadmap to add that feature.
