### ISSUE TITLE
Collect statistics about when the kit is flying to give information on "when to come back"

### ISSUE THREAD

**Issue by arthurlutz** [pagekite/PyPagekite#17]
PageKite is awesome for "temporarily" available websites. 

It would be great if the "Please try again later." could be more specific about when the web site is on. This would resemble "opening hours" like a physical place... Displaying the uptime of the website on a timeline could be a plus.

This could be optionnal (since it involves collecting data some users don't want to give away).

**Comment by pagekite** [comment]
This never got implemented, web-sites with "opening hours" haven't really become a thing, at least not enough to justify development time on a feature like this. Thanks for the idea though!
