### ISSUE TITLE
Wording on website

### ISSUE THREAD

**Issue by StFS** [pagekite/PyPagekite#25]
Hi.

Now that you have (or almost have) PageKite running on Android I think you should change the wording of the notification page when a service is not responding.

Currently it says:

    The computer may have been turned off
    The computer may be disconnected from the Internet
    The PageKite program may not be running

Maybe it would be better to refer to services and/or devices?

**Comment by pagekite** [comment]
Are Android users not aware that their phones are computers? :-)

But seriously, thanks for the suggestion, sorry for the very late reply. I'll take it under consideration, those messages could do with an update!
