### ISSUE TITLE
PageKite Connectivity Issue

### ISSUE THREAD

**Issue by sinhabis** [pagekite/PyPagekite#33]
Hello,

I am facing an issue wherein I am able to connect from some back-ends (using both domain name and ip address) but not able to connect from others (with domain name) but could connect using ip address of the front-end server. I am using my own front-end server. All this is setup internally within my corporate network. I have no clue what is causing this. I am not sure if this is to do with the front-end or back-end setup. Can anyone help me out?

Regards,
Bis

**Comment by pagekite** [comment]
Sorry we didn't reply to this in a timely fashion. It sounds like a networking issue if the same config works in some environments but not others. Either that, or you've left kites running and are trying to fly the same kite multiple times - that won't ever work reliably. :-)
