### ISSUE TITLE
Spec file issue

### ISSUE THREAD

**Issue by richard-allen** [pagekite/PyPagekite#35]
I was rebuilding the latest srpm from pagekite on my pidora (Fedora for Raspberry PI) because the one in the pidora repos is quite old when I noticed the following:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ImportError: No module named setuptools
error: Bad exit status from /var/tmp/rpm-tmp.aYYWai (%build)

After some googling (not a python guy) I found out this is fixable by installing the python-setuptools package.    Hence I suggest the following change to the spec file:

--- pagekite.spec.orig  2014-10-08 18:18:41.904090321 +0000
+++ pagekite.spec   2014-10-08 18:22:09.862125229 +0000
@@ -16,6 +16,7 @@
 BuildArch: noarch
 Vendor: PageKite Packaging Team packages@pagekite.net
 Requires: python-SocksipyChain
+BuildRequires: python-setuptools
 Url: http://pagekite.org/

 %description

This just adds the python-setuptools package as a build time only dependancy making rpmbuild exit neatly and telling the user exactly what is wrong.

**Comment by pagekite** [comment]
Belated.. but thank you!  Updating our RPM packages is a long overdue process; Fedora moves way faster than we do. :-/

**Comment by BjarniRunar** [comment]
PageKite is now being packaged by the distros (assuming we keep up and fix our Python 3 support), so this is largely irrelevant. Closing, thanks for filing!
