### ISSUE TITLE
socket activation support

### ISSUE THREAD

**Issue by zabbal** [pagekite/PyPagekite#36]
Would be excellent if pagekite could outsource messing around with sockets to systemd. This would be both simplify os integration part and would allow for smooth upgrades without loosing client requests. Some helpful information could be found in http://gfxmonk.net/2012/05/15/systemd-socket-activation-in-python.html

**Comment by pagekite** [comment]
Wow, systemd really does want to take over everything! :-)

I wouldn't reject a pull request for this, but this isn't on our roadmap at the moment.

**Comment by BjarniRunar** [comment]
Actually, on 2nd thought, I would reject this PR. This sounds like a large non-cross-platform complication. Thanks for the suggestion though! Closing. :smiley:
