### ISSUE TITLE
Incompatibility with Java v8

### ISSUE THREAD

**Issue by ValOgar** [pagekite/PyPagekite#37]
Situation:
Machine A (Running PageKite.py front-end-server) / We have created our own local network PageKite.py front-end-server exposed to internet. ( os - W7 professional).
Machine B (Running local web server)/ We have created our own local network PageKite.py back-end-client serving http/40000 and https/40443 to access local web server through PageKite.py reverse tunnel. (os –W7 embeded)

Procedure:
When we access Machine B/local web server through PageKite tunnel with Web browsers (Firefox/IExplorer/…) with HTTP or HTTPS protocol **everything working fine.**

When we access Machine B/local web server through PageKite tunnel with Web browsers (Firefox/IExplorer/…) with **HHTP or HTTPS** protocol and we are starting copy of java web application/ applet connected to local web server with "Java Web start /jp2launcher.exe" **(Java version 7) - everything working fine.**

When we access Machine B/local web server through PageKite tunnel with Web browsers (Firefox/IExplorer/…) with **HTTP** protocol and we are starting copy of java web application/ applet connected to local web server with “Java Web start /jp2launcher.exe” **(Java version 8) - everything working fine.**

When we access Machine B/local web server through PageKite tunnel with Web browsers (Firefox/IExplorer/…) with **HTTPS** protocol and we are starting copy of java web application/ applet connected to local web server with “Java Web start /jp2launcher.exe” **(Java version 8) – Java resets connection - Java log says … TROW … it is not possible to download/start java applet/application. (Confirmed by WireShark capture.)**

We tried to use Pagekite.me web service instead of our frond-end-server with exactly same results.
Do You have any evidence of incompatibility PageKite x Java v8?

Do you have any idea? 
Can you solve this issue?
Many thanks for help.
Ivo Polasek

**Comment by pagekite** [comment]
It is quite likely that the Java HTTPS client does not set the SNI headers required for PageKite to correctly tunnel the traffic. If you trust the relay and let pagekite.py handle the SSL instead of end-to-end tunneling of encrypted traffic, things might work.

Sorry about the late reply, I am going to close this as it's probably obsolete.
