### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by martinbrambati** [pagekite/PyPagekite#40]
Python 3 is not supported. Would be great to support the new python version as python web site encourage people to download python 3 instead of python 2.7

**Comment by pagekite** [comment]
We're currently supporting just about every Python from 2.2 up to 2.7, extending that to include Python 3 as well is more than we can handle in the near future. If the community steps up and helps out (this is open source after all) this might happen, but our new development efforts are focused on the high-performance rewrite in C, libpagekite - for which Python 2 and 3 bindings will eventually be developed.

Thanks for the suggestion though! I'm leaving this issue open in case someone else wants to take a look.

**Comment by BjarniRunar** [comment]
This is now on the "official roadmap."

Pagekite 0.5.9.x will be the last series of Python 2.x PageKite. Version 0.6.x and up will either be Python 3 only or will support Python 2.7 - 3.x.

**Comment by lzap** [comment]
Hello, your Fedora packager here :-)

Fedora is now marking Python 2.x as deprecated and will be ripping that off the distribution in January 2020. I have been warned already: https://bugzilla.redhat.com/show_bug.cgi?id=1738936

I am subscribing to this issue, as long as the code is Python3 ready and a release is out let me know and I will quickly push out an update. Thanks!

**Comment by BjarniRunar** [comment]
@lzap Someone should tell Fedora that they've misunderstood, Python 2.7 is finally **ready**, the devs have promised to stop changing it all the time! It's stable, at last!

:stuck_out_tongue_closed_eyes:

But seriously, sounds like this is more urgent than I'd hoped. I'll adjust my priorities accordingly. Thank you for bringing this to my attention, and thank you for packaging PageKite on Fedora!

**Comment by SunilMohanAdapa** [comment]
I believe the situation is similar in Debian:
https://wiki.debian.org/Python/2Removal
https://lists.debian.org/debian-python/2019/07/msg00080.html

**Comment by lzap** [comment]
I am just a soldier, I don't do politics. But I understand the pain :-(

GoLang is my new fav language: "Will you add ..." NO! :-)

**Comment by Argzero** [comment]
Any progress on this?

**Comment by ajgrf** [comment]
@Argzero I noticed that the work was started in #71, but I couldn't get it to run when I was packaging pagekite for GNU Guix.

**Comment by Argzero** [comment]
Hmm... I’ll take a look at it later during the week when I have some time. Thanks!

**Comment by BjarniRunar** [comment]
This is now top of my TODO list, I am actively working on this. If people want to help out, having some folks on #pagekite on IRC who can answer random questions I have might be helpful!

**Comment by BjarniRunar** [comment]
I just pushed and tagged v1.5.0.191126 - which merges all the amazing work from @SunilMohanAdapa, plus some minor fixes from me. We now support Python 3 and have dropped support for anything older than Python 2.6.

The packaging tooling still assumes Python 2.7, so there's still more work to be done, but this should be enough to unblock people who want to package this for distros that are dropping Python 2.x.

Thanks everyone for the help and patience, please let me know how this breaks...

**Comment by lzap** [comment]
Does this include python-socksipychain? Can you confirm which releases (tarballs preferably) are supposed to install and work in Python3 only environment? Thanks.
