### ISSUE TITLE
Bug in Debian 8 64bit with pyOpenSSL

### ISSUE THREAD

**Issue by jarrettchisholm** [pagekite/PyPagekite#41]
Installed pagekite using aptitude with instructions for debian package (added to sources.list).

SSL passthrough would work for one or two requests, then disconnect (static assets failed to load with 503 error).

I manually edited `/usr/share/pyshared/pagekite/compat.py` and disabled support for `pyOpenSSL` by changing `if socks.HAVE_PYOPENSSL:` to `if socks.HAVE_PYOPENSSL and False:`.  Now it works fine.

**Comment by lelit** [comment]
Thank you, this fixed it for me too!

**Comment by BjarniRunar** [comment]
There is a --nopyopenssl command-line flag to disable use of pyOpenSSL and prefer Python's native ssl library (or no ssl at all).

Is this my Debian package, or one the one from Debian themselves?

**Comment by jarrettchisholm** [comment]
The debian package would have been the one recommended on the PageKite site.

I didn't know about the `--nopyopenssl` flag, thanks for letting me know.

**Comment by tommag** [comment]
I can report this too ! 

I was trying to set up a VNC server tunneled in SSH, and kept having the message `packet_write_wait: Connection to UNKNOWN: Broken pipe` just after opening the VNC viewer.

Disabling pyOpenSSL seems to fix the problem.

I'm using the pagekite package from the Debian repos.

**Comment by robbynshaw** [comment]
Thanks so much for the tip guys. And especially thanks to you BjarniRunar. This fixed the issue that I was having with images not loading all the way. So awesome. Thanks!

**Comment by BjarniRunar** [comment]
I am pretty sure this got fixed long ago. Closing, thank you all for participating in the discussion.
