### ISSUE TITLE
Pagekit in frontend mode trying to find server to connect 

### ISSUE THREAD

**Issue by bobelev** [pagekite/PyPagekite#46]
I run pagekite as own frontend and constantly see this repeating message:

```
debug=Not sure which servers to contact, making no changes
```

**Comment by sabrehagen** [comment]
getting this also when successfully running `pagekite` in user mode, but when running as a system service this continually prints to the log. i'm using `~/.pagekite.rc` to configure my instance, and i'm guessing it's not referencing this when run as a system service. how can this file be respected when running as a system service?

**Comment by tboulogne** [comment]
get same.

Anyway to solve this ?

**Comment by bobelev** [comment]
> Anyway to solve this ?

I'm just using `./pagekite.py | grep -v 'Not sure which servers to contact'`

**Comment by tboulogne** [comment]
thanks @bobelev.

Try this and did not find interesting infos to solve. Could you define more your tip please ?

**Comment by DasBasti** [comment]
Did you edit your settings corectly?
I had that problem when I freshly installed it and the file /etc/pagekite.d/80_httpd.rc was not there.
You can move /etc/pagekite.d/80_httpd.rc.sample to get it.

**Comment by boskote** [comment]
I am seeing the same problem on a pagekite instance configured only as a backend. I am using the default config files as much as possible, pagekite is running as a service, and I have renamed 80.httpd.rc.sample to 80.httpd.rc. These are the two lines that are flooding my log file:
```
ts=58b7c3ac; t=2017-03-02T07:03:08; ll=21; debug=Preferred:
ts=58b7c3ac; t=2017-03-02T07:03:08; ll=22; debug=Not sure which servers to contact, making no changes.
```
And when I don't comment out the example line in 80.httpd.rc, I get a different error appearing frequently in the log:
```
ts=58b7c500; t=2017-03-02T07:08:48; ll=22; disconnect=x.x.x.x:x
ts=58b7c505; t=2017-03-02T07:08:53; ll=23; disconnect=x.x.x.x:x
```

**Comment by thanhbui-nixu** [comment]
No solution for this yet?

**Comment by BjarniRunar** [comment]
Pagekite.py version 1.5.1+ disables a lot of debugging noise by default, which used to go directly to the logs. This is one such message.

People using 1.0.x will continue to see this, as I don't want to change behavior there. The Debian package in the pagekite.net repo is still 1.0.x, but it should get updated to 1.5.x sometime this summer.
