### ISSUE TITLE
--host is ignored for IPv6 listeners

### ISSUE THREAD

**Issue by dantman** [pagekite/PyPagekite#50]
pagekite appears to be ignoing the address I specify in --host when it binds to the https port.

According to the logs pagekite thinks it's binding to the correct address, but in fact when you look at netstat it has actually bound to the global `:::443`.

This is a problem because it means that despite having 2 separate IPs so pagekite uses one and my actual webservers use the other, pagekite still conflicts with the https port my websites use.

Here's the relevant netstat output:

``` console
$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.1.6:80             0.0.0.0:*               LISTEN      11558/python    
...
tcp6       0      0 :::443                  :::*                    LISTEN      11558/python    
...
```

As you can see `11558` is pagekite.

``` console
sudo systemctl status pagekite
● pagekite.service - LSB: PageKite system service
   Loaded: loaded (/etc/init.d/pagekite)
   Active: active (running) since Thu 2016-02-04 19:00:46 UTC; 7min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11388 ExecStop=/etc/init.d/pagekite stop (code=exited, status=0/SUCCESS)
  Process: 11408 ExecStart=/etc/init.d/pagekite start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/pagekite.service
           ├─11418 /usr/bin/daemon --pidfile /var/run/pagekite.pid.wrapper --noconfig --unsafe --respawn --delay=60 --name=pagekite -- ...
           └─11558 /usr/bin/python /usr/bin/pagekite --pidfile /var/run/pagekite.pid --clean --runas=daemon:daemon --logfile=/var/log/p...
```

Here is my config (`/etc/pagekite.d/20_frontends.rc`):

```
#################################[ This file is placed in the Public Domain. ]#
# Front-end selection
#
# Front-ends accept incoming requests on your behalf and forward them to
# your PageKite, which in turn forwards them to the actual server.  You
# probably need at least one, the service defaults will choose one for you.

# Use the pagekite.net service defaults.
# defaults

# If you want to use your own, use something like:
#     frontend = hostname:port
# or:
#     frontends = COUNT:dnsname:port

isfrontend
runas=www-data:www-data
host=10.0.1.6
ports=80,443
protos=http,https
domain=http,https:...
```

And here's part of the pagekite log during startup:

```
started=/usr/bin/pagekite; ll=0; ts=56b3a092; argv=--pidfile /var/run/pagekite.pid --clean --runas=daemon:daemon --logfile=/var/log/pagekite/pagekite.log --optdir=/etc/pagekite.d --noloop; platform=linux2; version=0.5.8a; t=2016-02-04T19:03:46; ca_certs=/etc/ssl/certs/ca-certificates.crt; optfile_/etc/pagekite.d/20_frontends.rc=ok
info=Collecting entropy for a secure secret.; ll=1; ts=56b3a092; t=2016-02-04T19:03:46
debug=Seeded signatures using /dev/urandom, hooray!; ll=2; ts=56b3a092; t=2016-02-04T19:03:46
debug=UiComm: Created; ll=3; ts=56b3a092; t=2016-02-04T19:03:46
id=s0; ll=4; listen=10.0.1.6:80; ts=56b3a092; t=2016-02-04T19:03:46
id=s1; ll=5; listen=10.0.1.6:443; ts=56b3a092; t=2016-02-04T19:03:46
ts=56b3a092; t=2016-02-04T19:03:46; ll=6; uid=33; gid=33
ts=56b3a092; t=2016-02-04T19:03:46; ll=7; debug=TunnelManager: loop #1, interval=5
```

**Comment by pagekite** [comment]
Thanks for reporting this. This is probably a bug in how we're doing IPv6; I'm going to update the subject to say so.

**Comment by BjarniRunar** [comment]
I have tweaked the code to not attempt an IPv6 listen if the --host argument looks like an IPv4 address.

I think for whatever reason, Python was interpreting the IP address as a hostname, failing to resolve it to an IPv6 address and so defaulting to listening on all available interfaces - which was global on 443 because nothing else had already grabbed the port, but a specific interface on 80 because the others were unavailable.

I'm just guessing though; there's nothing in my code that treats 80 differently from 443, all listen ports are handled the same. So the difference in behaviour is lower level and likely to be related to your specific environment.

I realize it's a bit late, but there is a testing Debian package at https://pagekite.net/pk/deb/pool/main/p/pagekite/ which you could try installing if you'd like to confirm whether this works for you.

**Comment by BjarniRunar** [comment]
I'm going to assume this is fixed.
