### ISSUE TITLE
pagekite.py doesn't start if Python 3 is the default Python

### ISSUE THREAD

**Issue by JohanLorenzo** [pagekite/PyPagekite#52]
Thanks for your tool guys!

On my Linux distro, the first line of `pagekite.py` 

```
#!/usr/bin/python
```

resolves to Python 3 . I think we can change this generated line to

```
#!/usr/bin/env python2
```

This would also allow the use of virtualenv.

What do you guys think?

**Comment by JohanLorenzo** [comment]
I believe it should be fixed by pagekite/PyBreeder#1

**Comment by BjarniRunar** [comment]
@renatocan I'm coming to the conclusion that that is indeed the correct solution to this - to shift PageKite's compatibility window from 2.2-2.7, to 2.6-3.x. I think that is possible, but I need to do a bit more research.

**Comment by SunilMohanAdapa** [comment]
Consider dropping Python 2 support entirely since Pagekite is not an application and not a library and Python 3 is widely available. This will make the task much simpler.

**Comment by BjarniRunar** [comment]
@SunilMohanAdapa We are trying to support LTS distros like RHEL and CentOS, so that's not an option.

**Comment by BjarniRunar** [comment]
PageKite 0.6.x will be Python 3 compatible and will drop support for anything older than Python 2.7. I plan to start working on this, this year.
