### ISSUE TITLE
Pagekite deb repo cannot be installed on 16.04 LTS

### ISSUE THREAD

**Issue by dantman** [pagekite/PyPagekite#55]
Pagekite is no longer installable via the [deb package](https://pagekite.net/wiki/Howto/GNULinux/DebianPackage/) anymore on Ubuntu 16.04 LTS.

It seems that the `python-support` package no longer exists. Ubuntu's [python-socksipychain](http://packages.ubuntu.com/xenial/python-socksipychain) package does not depend on it, however the Pagekite repo overrides `python-socksipychain` with a version that does depend on `python-support` but does not provide a `python-support` package to go with it.

``` console
$ sudo apt-get install pagekite
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pagekite : Depends: python-support (>= 0.90.0) but it is not installable
            Depends: python-socksipychain (>= 2.0.15) but it is not going to be installed
```

**Comment by Mukopaje** [comment]
//try this worked for me.
wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb

**Comment by BjarniRunar** [comment]
Thanks for reporting this. Not sure how best to work around this without starting to build custom packages for Ubuntu, any suggestions are welcome!

**Comment by Mukopaje** [comment]
Well I think this has now been fixed as you can now install direct from the repository

**Comment by BjarniRunar** [comment]
Thanks @Mukopaje !

**Comment by pguth** [comment]
That's maybe worth pointing out in the tutorial here: https://pagekite.net/wiki/Howto/GNULinux/DebianPackage/#formPostTarget
