### ISSUE TITLE
Support IRCv3 CAP LS as first command in IRC connection

### ISSUE THREAD

**Issue by freaktechnik** [pagekite/PyPagekite#57]
From what I understand IRC connections currently fail if the client sends a `CAP LS` before `PASS` or `NICK`. However almost any client supporting IRC v3 will send `CAP LS` before anything else, meaning it will fail to connect. `CAP LS` is sent before anything else since it might affect the negotiation as capabilities are added (so any other `CAP` command may follow before `NICK` or `PASS` is sent).

See also http://ircv3.net/specs/core/capability-negotiation-3.1.html#the-cap-ls-subcommand

**Comment by pagekite** [comment]
IRC support isn't really a priority for us at this point; I'd accept a pull request fixing this but I'm probably not going to find time to work on it any time soon.

**Comment by BjarniRunar** [comment]
Just a heads' up, time is running out on this issue. The 5.9.x series is most likely the last that will support the IRC protocols at all. Version 0.6.x will most likely remove the protocol entirely - unless someone speaks up.

I'm pretty much convinced that the "right" way to support arbitrary protocols, such as IRC, is to use end-to-end TLS and rely on the SNI-based routing.
