### ISSUE TITLE
Pagekite FE 'unknown' fallback not available when using wildcard in --domain

### ISSUE THREAD

**Issue by jasonhadi** [pagekite/PyPagekite#58]
I'd like to use the special 'unknown' hostname to catch unrecognised domains. It works as suggested in the README: 
` --domain=http,https:foo.bar.com:YOURSECRET --service_on=https:unknown:localhost:8090:`
However, when using a wildcard, the local backend doesn't start and unrecognised domains aren't forwarded.
`--domain=http,https:*.bar.com:YOURSECRET  --service_on=https:unknown:localhost:8090:`

Am I missing something in the Pagekite configuration to make this work? Thanks in advance!

**Comment by cyberquarks** [comment]
@jasonhadi your post was like 3 years ago, have you managed to get around the issue? 
Maybe this is related to https://github.com/pagekite/PyPagekite/issues/83

**Comment by BjarniRunar** [comment]
This isn't a bug, this is a request for a new feature? PageKite has never supported wildcards at the backend, which was a deliberate choice. People are welcome to try and convince me it was a bad choice, but a 3 year old issue isn't the right place for that discussion so I'm going to close this.

Thanks for your feedback and interest!

**Comment by cyberquarks** [comment]
@BjarniRunar I can say that it's not a bad choice but rather maybe something that was needed by the majority of users of Pagekite. There are two work around that I can think of at the moment and I am posting here as (a sort of) answer to the "issue" 

Work-around through NGINX server (assuming your are running your own Pagekite front-end). First need to setup nginx that can handle HTTPS (i.e certs etc) have Pagekite run on port `8080` and `8443` for example, then proxy forward nginx request to `localhost:8080` changing the host header to something that Pagekite actually serves. 

The backend (the one running on local machine) would connect to Pagekite through port `8080` or `8443` (haven't tried it) 

In short this approach will terminate the secure connection and wildcards at NGINX then it will just forward (unsecured) within the front-end server to Pagekite, the tunnel to the local machine (from the front-end) I assume must be secure, I haven't tinkered the code base yet to know this. 

"What is needed here" is that you have your local machine server to be able to parse the host header to handle requests that came in.  Here's a sketch of something I can think of:

```
+----------------------------+
|  something.yourdomain.com  |        +---------------------------------+        +---------------------------+              +---------------------------+
|  OR api.yourdomain.com     | ----\  | NGINX Server                    | ----\  | Pagekite (e.g Port 8080)  |   /-------\  | your local machine server |
|  OR www.otherdomain.com    | ----/  | Forward to localhost:8080       | ----/  |                           |   \-------/  |                           |
|                            |        +---------------------------------+        +---------------------------+    (Tunnel)  +---------------------------+
+----------------------------+        (NGINX handles Wildcard, HTTPS, etc.)                                                 (connected e.g. backend.yourdomain.com)
                                      (and note forward must keep host)
```

From here (I think) the wildcard subdomain is handled plus gets tunneled to local machine.

**Comment by BjarniRunar** [comment]
Hey, I closed this issue for a reason! Let's move the discussion elsewhere.

However, for the record - putting an HTTP proxy in front of PageKite usually does not work. I've tried! :smiley:
