### ISSUE TITLE
SSL Write Pending Error When Using Self-Deployed Front-End

### ISSUE THREAD

**Issue by brandonhudson** [pagekite/PyPagekite#62]
Hi All,

I'm hoping you can offer some thoughts on why I might be running into this situation. I'm running our own deployed Pagekite front-end with SSL support, forwarding requests from back-end server nodes on port 80 to 80 and 443 on the front-end. My command configuration is the following:

## Frontend:
```
/var/pagekite-frontend/pagekite.py --isfrontend --ports=80,2222,443 --protos=http,raw,https --domain=http,raw,https:*.ccs.house:[SECRET] --rawports=virtual --logfile=/home/bhudson/pagekite.log --clean --tls_endpoint=frontend-ssl.ccs.house:/home/bhudson/__frontend.pem --tls_endpoint=*.ccs.house:/home/bhudson/__frontend.pem --daemonize
```

## Backend:
```
pagekite --frontends=1:frontend-ssl.ccs.house:443 --service_on=raw/2222:corbett.ccs.house:localhost:22:[SECRET] --service_on=http:corbett.ccs.house:localhost:80:[SECRET] --daemonize --dyndns=https://[USER]:[PASS]@dashboard.connexus.xyz/api/external/device/199/network/proxy-dyndns?hostname=%(domain)s&ip=%(ip)s --fe_certname=frontend-ssl.ccs.house --ca_cert=/var/secure/certs/__ccs_house.ca-bundle --logfile=/home/bhudson/pagekite.log
```

I am able to successfully access the device via RAW/2222 (SSH), but whenever I attempt to load HTTP/HTTPS, the backend drops connection to the frontend and logs the `Error sending (SSL): [('SSL routines', 'ssl3_write_pending', 'bad write retry')]; id=s0` error. We have several deployed backends in production using this same configuration, but only this system seems to run into trouble.

## System Information
Ubuntu 16.04
Python 2.7.12
Python 3.5.2
PHP 7.0.18-0ubuntu0.16.04.1

I've also verified that each of the other systems that are operating correctly have the same versions of Python, PHP, and OS. 

Here are the full logs for the event.

## Logs
```
started=/usr/bin/pagekite; ll=0; ts=5af626da; argv=--frontends=1:frontend-ssl.ccs.house:443 --service_on=raw/2222:corbett.ccs.house:localhost:22:[SECRET] --service_on=http:corbett.ccs.house:localhost:80:[SECRET] --daemonize --dyndns=https://[USER]:[PASS]@dashboard.connexusdev.xyz/api/external/device/199/network/proxy-dyndns?hostname=%(domain)s&ip=%(ip)s --fe_certname=frontend-ssl.ccs.house --ca_cert=/var/secure/certs/__ccs_house.ca-bundle --logfile=/home/bhudson/pagekite.log; platform=linux2; version=0.5.8a; t=2018-05-11T23:27:22; ca_certs=/var/secure/certs/__ccs_house.ca-bundle
info=Collecting entropy for a secure secret.; ll=1; ts=5af626da; t=2018-05-11T23:27:22
debug=Seeded signatures using /dev/urandom, hooray!; ll=2; ts=5af626da; t=2018-05-11T23:27:22
debug=UiComm: Created; ll=3; ts=5af626da; t=2018-05-11T23:27:22
ts=5af626db; t=2018-05-11T23:27:23; ll=4; debug=TunnelManager: loop #1, interval=5ts=5af626db; t=2018-05-11T23:27:23; ll=5; debug=Entering main epoll loop
ts=5af626e0; t=2018-05-11T23:27:28; ll=19; on_port=80; proto=http; domain=corbett.ccs.house; is=BE; remote_ip=::ffff:64.201.233.154; id=s2
ts=5af626e0; t=2018-05-11T23:27:28; ll=1a; on_port=80; proto=http; domain=corbett.ccs.house; is=BE; remote_ip=::ffff:64.201.233.154; id=s3
ts=5af626e0; t=2018-05-11T23:27:28; ll=1b; on_port=80; proto=http; domain=corbett.ccs.house; is=BE; remote_ip=::ffff:64.201.233.154; id=s4
ts=5af626e0; t=2018-05-11T23:27:28; ll=1c; on_port=80; proto=http; domain=corbett.ccs.house; is=BE; remote_ip=::ffff:64.201.233.154; id=s5
ts=5af626e0; t=2018-05-11T23:27:28; ll=1d; info=Error sending (SSL): [('SSL routines', 'ssl3_write_pending', 'bad write retry')]; id=s0
ts=5af626e0; t=2018-05-11T23:27:28; ll=1e; wrote=3633; wbps=67; read=14785; eof=1; id=s1
ts=5af626e0; t=2018-05-11T23:27:28; ll=1f; wrote=719; wbps=0; read=0; eof=1; id=s5
ts=5af626e0; t=2018-05-11T23:27:28; ll=20; wrote=731; wbps=0; read=11272; eof=1; id=s3
ts=5af626e0; t=2018-05-11T23:27:28; ll=21; wrote=1332; wbps=665; read=2235; eof=1; id=s4
ts=5af626e0; t=2018-05-11T23:27:28; ll=22; wrote=1286; wbps=582; read=17937; eof=1; id=s2
ts=5af626e0; t=2018-05-11T23:27:28; ll=23; wrote=31805; wbps=285; read=7816; eof=1; id=s0
```

Any thoughts you can offer on this are much appreciated.

~Brandon

**Comment by brandonhudson** [comment]
I was able to solve this by using `--nopyopenssl` in the command arguments referenced in https://github.com/pagekite/PyPagekite/issues/41. It would be awesome if these such command line arguments were all documented in the GitHub docs - I'd be more than willing to assist with that if there's a list of all command line arguments somewhere.

**Comment by BjarniRunar** [comment]
Hi @brandonhudson, thanks for reporting this!

I still don't really understand what the problem is here, I haven't been able to track it down myself.  Something subtle changed in OpenSSL or in the Python bindings at some point, and I'm not sure what. 

Regarding documentation - the man page is supposed to contain all the arguments, but that one (and `--nossl`) seem to have been forgotten. I've added both in my local tree, they'll go live next time I push up.

**Comment by brandonhudson** [comment]
I believe this is good to close now that the docs are added - thanks for the assistance!
