### ISSUE TITLE
Prevent DNS IPv6 lookup

### ISSUE THREAD

**Issue by matteodisabatino** [pagekite/PyPagekite#65]
Hi and first of all thanks for building this software :-)
These days I was testing it for a project of mine, all worked fine until I had to use 3G network: it seems that some carriers DNS don't resolve hostnames to IPv6 properly and the result is that I'm unable to connect to my server.
To prevent this I decided to fork the project and make [this change](https://github.com/matteodisabatino/PyPagekite/commit/a20c565c72f9aa111b6df10d928961a7f175e29a) that exclude all IPv6 addresses from addresses list. Obviously this change solve nothing but my problem and (probably) it could be dangerous in the near future.
To solve this problem permanently I think it could the useful to add to PageKite an option called --use-ipv4-only or maybe --prevent-ipv6-lookup or whatever name you would like to give it that allows PageKite to use IPv4 only. To get the goal, I suppose it's just necessary to add an if statement within my code.
Cheers.

**Comment by BjarniRunar** [comment]
Thank you for filing this and sharing your patch.

It's an interesting problem, I wonder if there's a gentler way to resolve the issue though? Better than disabling v4 or v6, it would probably make more sense for the server pings to be smart enough to detect when one type of address isn't working and just use the other.

**Comment by matteodisabatino** [comment]
Hi Bjarni! Sorry for late, I was in vacation :-)
Anyway, yeah you gotta reason I hope to work on this very :-)
