### ISSUE TITLE
Front-end crash with "Bad file descriptor" error

### ISSUE THREAD

**Issue by alankeny** [pagekite/PyPagekite#68]
I'm running pagekite.py v0.5.9.3 as a front-end on a VPS.  At least once a day I have to restart the front-end, because the server has crashed with the following errors:

````
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d92; accept=~87.63:52996; id=s0
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d93; on_port=80; proto=http; domain=A.B.C.D; is=BE; remote_ip=::ffff:172.104.87.63; id=s3ec
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d94; on_port=80; proto=http; domain=A.B.C.D; is=BE; remote_ip=::ffff:172.104.87.63; id=s3ed
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d95; wrote=411; wbps=0; read=0; eof=1; id=s3ea/~87.63:52996
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d96; debug=No back-end; on_port=80; proto=http; domain=A.B.C.D; is=FE; id=s3ea/~87.63:52996
Traceback (most recent call last):
  File "<string>", line 3570, in Main
  File "<string>", line 3528, in Start
  File "<string>", line 3391, in Loop
  File "<string>", line 3251, in ProcessReadable
  File "<string>", line 404, in ReadData
  File "<string>", line 726, in ProcessData
  File "<string>", line 639, in ProcessData
  File "<string>", line 1423, in ProcessLine
  File "<string>", line 1587, in ProcessParsedHttp
  File "<string>", line 599, in HTTP_Unavail
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/local/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d97; debug=AuthThread: done
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d98; debug=HttpUiThread: done
ts=5c517b9b; t=2019-01-30T10:25:31; ll=3d99; debug=UiCommunicator: done
ts=5c517b9c; t=2019-01-30T10:25:32; ll=3d9a; debug=TunnelManager: done

Error: [Errno 9] Bad file descriptor
````

I've replaced the public IP of the VPS with A.B.C.D and the domain name with example.net in the posted logs and config.  The front-end is configured with the following:

````
service_on=http:unknown:127.0.0.1:80:
service_on=https:unknown:127.0.0.1:443:
````

Apache is running on localhost ports 80 and 443.  Port 80 simply redirects to HTTPS.  The unknown 443 serves a single static page.  The known back-end servers match this:

````
domain=https:*.example.net:mysecretkitestring
````

Based on the logged error, I thought something was going wrong with Apache, so that it had stopped serving HTTP when the host name in the URL was the A.B.C.D IP address.  I reconfigured the Pagekite front-end, so it would serve HTTP for the IP address host name directly with the following:

````
webpath=A.B.C.D/80:/:default:/usr/local/www/apache24/data
service_on=http:A.B.C.D:localhost:builtin:@kitesecret
service_cfg=A.B.C.D/80:indexes:True
````

After this change Pagekite served requests for http://A.B.C.D/ even when Apache was stopped.  I still got the same error in the logs, when the front-end crashed over night.  Pagekite is running on Python 2.7.15.

Any idea what's causing the front-end to crash or how I can debug this further?

**Comment by BjarniRunar** [comment]
I'm sorry this never got answered. :disappointed: 

I'm going to assume the question is obsolete and close.
