### ISSUE TITLE
Run Pagekite on Windows Embedded Compact 7

### ISSUE THREAD

**Issue by pinkynrg** [pagekite/PyPagekite#70]
Is there any way to run Pagekite on Windows Embedded Compact 7?

**Comment by BjarniRunar** [comment]
What's that? :stuck_out_tongue:

I don't know. If you find out that it *almost* works and you'd like to propose some changes to make it work better, please feel free to file an issue or a pull request. But since this is not a support forum I'm closing this issue. Good luck!
