### ISSUE TITLE
Interactive signup is broken in latest release

### ISSUE THREAD

**Issue by ajgrf** [pagekite/PyPagekite#73]
I'm trying out the new Python 3 release. (Woohoo!) The networking code seems to work great so far, but the interactive signup no longer prompts correctly. Maybe the terminal is buffering the output, because I can only see the questions after hitting enter or killing pagekite.

os: Guix System
pagekite: 1.5.0.191126
python: 3.7.4
python-six: 1.12.0
python-socksipychain: 2.1.0

**Comment by BjarniRunar** [comment]
Thank you for reporting this! I'll take a look soonish.
