### ISSUE TITLE
backend tunnel encryption

### ISSUE THREAD

**Issue by krazy707** [pagekite/PyPagekite#74]
Hi,  so i have installed  hosted version of the frontend , and am able to do http,  at this point , am trying to encrypt between frontend and backend, at the tunnel, followed the steps of creating self signed cert, and installing that on both frontend and backend,  struggled for some time, but at the end it got connected, however,  i need to confirm it's encrypted tunnel,  how do i check  or confirm that tunnel is encrypted, and using ssl.  

thanks

**Comment by pagekite** [comment]
You could try using something like wireshark or tcpdump?

You can also run the connector with --logfile=stdio --debugio and see if the very-verbose debug output looks correct.
