### ISSUE TITLE
DynDNS and proxy errors

### ISSUE THREAD

**Issue by hrafnkelle** [pagekite/PyPagekite#8]
the http object used in pagekite honours the system wide proxy settings. If that proxy requires authentication the dyndns update will fail with an error. pagekite will repeatedly keep trying.

Should stop trying or fall back to a slower rate.

**Comment by BjarniRunar** [comment]
I am pretty sure PageKite is much less aggressive about this than it was when this was reported. I'm gonna say we fixed this one along the way. :grinning:
