### ISSUE TITLE
Pagekite fails to run

### ISSUE THREAD

**Issue by drumwhizz** [pagekite/PyPagekite#80]
Don't know if this is a configuration issue, but I have just downloaded v1.0.1.200424 and tried to run it on a laptop running Ubuntu 20.04 and Python 2.7.18rc1 and got the following crash..

root@rob-Lenovo-V110-15ISK:~# pagekite.py 
Traceback (most recent call last):
  File "/usr/local/bin/pagekite.py", line 254, in <module>
    exec __FILES[".SELF/sockschain/__init__.py"] in m.__dict__
  File "<string>", line 49, in <module>
ImportError: No module named six

**Comment by SunilMohanAdapa** [comment]
python-six package is needed. Install it with 'sudo apt install python-six' from 'universe' repositories.

Python 2 is no longer supported on Ubuntu. Trying Python 3 is another way. `python3 /usr/local/bin/pagekite.py`

**Comment by cguess** [comment]
I can recreate this on Ubuntu 20.04 (upgraded from 19.10, where this was working) as well. `sudo apt install python-six` does indeed fix this.

**Comment by BjarniRunar** [comment]
Thank you for reporting this!

I hope to make a release this week that fixes this issue under Python 2, but will work under Python 3 as well.

At first this will only be the bundled single-file pagekite.py (the Debian package will be Python 2 for a little longer while I work out compatibility issues).

**Comment by BjarniRunar** [comment]
This should be fixed now. Thank you for reporting this!
