### ISSUE TITLE
Ubuntu 20.04 SSL Verification Error

### ISSUE THREAD

**Issue by cguess** [pagekite/PyPagekite#81]
After upgrading to Ubuntu 20.04 from 19.10 I am getting the following errors when running the latest version of PageKite:
```
>>> Hello! This is pagekite.py v1.0.1.200424.                   [CTRL+C = Stop]
!!! Failed to connect to 45.79.143.125:443
    Unable to verify SSL certificates!
     - Using standard Python ssl: try installing pyOpenSSL?
     - CA certificates loaded: /usr/local/bin/pagekite.py
     - Would accept a certificate for: b5p.us
     - Would accept a certificate for: frontends.b5p.us
     - Would accept a certificate for: pagekite.net
     - Would accept a certificate for: pagekite.me
     - Would accept a certificate for: pagekite.com
     - Would accept a certificate for: pagekite.org
     - Would accept a certificate for: testing.is
     - Would accept a certificate for: 302.is
     - Check your system clock (dates matter)
     - Beware firewalls that intercept outgoing SSL/TLS connections!
     - Danger Zone: use --fe_nocertcheck to connect insecurely.
!!! Failed to connect to 45.79.218.26:443
!!! Failed to connect to 23.92.25.237:443
!!! Failed to connect to 151.236.220.126:443
!!! Failed to connect to 139.162.151.43:443
!!! Failed to connect to 94.130.75.194:443
```

As in #79 this is fixed by installing the proper dependency:
```
sudo apt-get install python-openssl
```

**Comment by BjarniRunar** [comment]
That shouldn't be necessary, something must have changed/broken in the native Python ssl module. Which is weird, I thought Python 2 wasn't just stable, it's EOL. Thank you for the heads up.

**Comment by BjarniRunar** [comment]
Just wanted to confirm I've reproduced this, but I still don't know what is going on.

Installing python-openssl is the recommended workaround for now (and this happens by default if you use the Debian package, which Ubuntu users should consider doing: https://pagekite.net/wiki/Howto/GNULinux/DebianPackage/ )

**Comment by BjarniRunar** [comment]
Found and fixed in my local tree! Will be making a new release soon. Thanks again for reporting this.

**Comment by cyberquarks** [comment]
@BjarniRunar a side question, how do you install SSL certificate with Pagekite front-end? Normally if I am using nginx I would do something like upload the SSL certificate to some folder and make nginx server config point to that SSL and if I am going to install multiple SSL for multiple domains I would normally create config for each domain and reload nginx service, sort of, although I have an automation for this. I am wondering if how it is done with Pagekite front-end, I mean to install wildcard certificate and also multiple certs?

**Comment by BjarniRunar** [comment]
@cguess I have pushed a new pagekite.py (v1.5.2) to https://pagekite.net/pk/pagekite.py - this should fix the problem you've described, and should also work with python 3. If you could confirm this works for you, we can close this? :-)

@cyberquarks You can install certs at either the front- or back-end, depending on whether you want end-to-end encryption or not. There is a fair bit of discussion of TLS configuration in `doc/README.md`.

**Comment by BjarniRunar** [comment]
The updated version is now fully shipped and AFAICT it works. Closing!
