### ISSUE TITLE
Unable to set wildcard kites

### ISSUE THREAD

**Issue by cyberquarks** [pagekite/PyPagekite#83]
In order to fly kites it needs to be set into the `/etc/pagekite.d/10_account.rc` file.

So if you set 

```
kitename   = www.yourdomain.com
kitesecret = examplepassword2
```

It works but if you do

```
kitename   = *.yourdomain.com
kitesecret = examplepassword2
```

Then do 

`./pagekite.py --clean --frontend=*.yourdomain.com:80 --service_on=http:*.yourdomain.com:localhost:8080:examplepassword2`

It throws 

```
>>> Hello! This is pagekite.py v1.0.1.200424.                   [CTRL+C = Stop]
    It looks like your Internet connection might be down! Will retry soon.
     - Check whether you can ping pagekite.net or google.com
     - Check whether `*.yourdomain.com` can be looked up in DNS
 << pagekite.py [down]     No kites ready to fly.  Waiting...
```

Not sure if my configuration is not right or something, but the idea is to be able to forward all requests from `*.yourdomain.com` (from any CNAME) to the target local machine backend server.

**Comment by cyberquarks** [comment]
The solution maybe to just "add more kites" in the configuration but that presents multiple problems:

For example, you have manually or create a script to update `10_account.rc` and reload the pagekite service and if you're serving like 100's of sites then that will impose unwanted downtime to other sites. Second, if you're not serving websites but for example a backend server, e.g. REST API server then that too will be imposed with unwanted downtime. 

You might have a server that can handle request from multiple domain / subdomains e.g

```
+----------------------------+
|  something.yourdomain.com  |        +---------------------------------+        +---------------------------+
|  OR rest.yourdomain.com    | ----\  | your pagekite front-end         | ----\  | your local machine server |
|  OR www.otherdomain.com    | ----/  | (e.g on Linode, AWS or any VPS) | ----/  |                           |
|                            |        +---------------------------------+        +---------------------------+
+----------------------------+

```

In this example, the domain `yourdomain.com` have A record pointing to the Public IP of the Pagekite front-end. The `www.otherdomain.com` however points to the Pagekite front-end via it's CNAME `www` pointed to something like `subdomain.yourdomain.com` this is where the wildcard subdomain is useful, you can point as many subdomains and domains to your local machine server.

**Comment by cyberquarks** [comment]
After testing for few hours I found that apparently Pagekite does not rely on kite names from the `/etc/pagekite.d/10_account.rc` in the front-end server and I run and set any subdomain from my local machine: 

`./pagekite.py --clean --frontend=any-subdomain.yourdomain.com:80 --service_on=http:any-subdomain.yourdomain.com:localhost:8080:examplepassword2`

Although I can't still achieve to "tell" the front-end server to forward all subdomain to my local machine as such:

`./pagekite.py --clean --frontend=*.yourdomain.com:80 --service_on=http:*.yourdomain.com:localhost:8080:examplepassword2`

**Comment by cyberquarks** [comment]
...I am thinking of a solution with Pagekite, I may just change it's port from 80,443 to 8080,8443 then put an nginx in from of it that will proxy forward to (in the cloud server) subdomain.yourdomain.com:8080 or subdomain.yourdomain.com:8443 and one server (my local machine) can pick it up. Since the problem when someone access my server in form of subdomain.yourdomain.com:80 then if there's no local machine running with that kite name the server (pagekite) shows "Sorry! (fe) " the idea is to be able, my server, to handle all request from any subdomain, so I am thinking of such approach as a work around.

**Comment by BjarniRunar** [comment]
I am unconvinced that wildcard kites are worth implementing; doing this well will double the amount of lookup work the frontend needs to do for unrecognized incoming requests, for a feature which I consider mostly a bad idea.

Why a bad idea? I rather strongly believe that server configurations should be as explicit as possible. Typos in URLs should result in error messages - if they just magically work, there is nothing to prevent people from creating broken links all over the place. It is also an important security principle that unexpected requests be rejected, not passed on to a potentially vulnerable server.

I've often considered implementing this and always decided against it. I might accept a pull request, but as it stands I probably won't implement this myself.

**Comment by cyberquarks** [comment]
@BjarniRunar yes I think instead of wildcard kites a better solution is the one you mentioned here: https://github.com/pagekite/PyPagekite/issues/84

A "catch-all" running kite which have the same effect as wildcard kite.
